### ISSUE TITLE
Memory Error

### ISSUE THREAD

**Issue by jiezhao1219** [VolpeUSDOT/FTOT-Public#11]
In QS2, if we use a new schedule with day>=10 instead of a "default" schedule, "Memory Error" will occur in optimization steps. Is there any efficient way to solve this memory error for applying the multiple-step schedule?

**Comment by matthewpearlson** [comment]
Hi Jie. Thanks for reaching out about the memory error you are experiencing with QS2 and a 10 day schedule.

Can you confirm if you are using the 32 bit version or 64 bit version of python when you run?

The 32 bit version does run into memory errors, and this is a known issue for larger scenarios. In particular, 32-bit processes typically have a limit of ~2GB, after that the Memory Error is shown. 

The 64 bit version does not have a 2 GB limit, and can handle larger scenarios up to the limit of your computers memory. 

Please let us know which version you are using (32 vs 64 bit).

**Comment by jiezhao1219** [comment]
@matthewpearlson Hi Matthew, Thanks for your replay! 

I used the 32 bit version of Python for simulation. I think this should be the major reason for the Memory Error. I will change the Python version for large scenario simulation. 

Thank you for your explanation!
