### ISSUE TITLE
Installation Guide - remove Volpe-specific text

### ISSUE THREAD

**Issue by dflynn-volpe** [VolpeUSDOT/FTOT-Public#13]
The [installation guide](https://github.com/VolpeUSDOT/FTOT-Public/wiki/FTOT-Installation-Guide) includes two Volpe-specific steps, # 12 and 13. 

Better to replace that with more general text: 'Install with an appropriate license or connection to a license manager'.

**Comment by matthewpearlson** [comment]
thanks @dflynn-volpe - this is good feedback. we will discuss in the team meeting today.

@aobergdc  -- thoughts on updating this one?

**Comment by aobergdc** [comment]
@dflynn-volpe @matthewpearlson  I don't see a problem with making this change. I still think we'll want to include a note either at the top or in this step noting who USDOT-Volpe users should contact for licensing information/Volpe-specific installation instructions.
