### ISSUE TITLE
Pipeline issue

### ISSUE THREAD

**Issue by cdd8sb** [VolpeUSDOT/FTOT-Public#35]
Here is the zip file for my project. It has the input data, the run file and the scenario file.

[Virginia High.zip](https://github.com/VolpeUSDOT/FTOT-Public/files/7649522/Virginia.High.zip)

**Comment by cdd8sb** [comment]
Here is the g_log from my run a couple days ago with the road turned off.
[g_log_2021_12_07_20-59-21.log](https://github.com/VolpeUSDOT/FTOT-Public/files/7694268/g_log_2021_12_07_20-59-21.log)

**Comment by kzhang81** [comment]
Hi @cdd8sb -- thanks for closing the issue! With public release 2022.1, this bug with the Network Density Reduction (NDR) functionality has been resolved. Results for NDR_On = True and NDR_On = False now match, with the same time savings for NDR.
